"""Recreate table

Revision ID: 50ae7d1a8db2
Revises: 82b13e55681c
Create Date: 2021-08-15 22:29:48.473187

"""

# revision identifiers, used by Alembic.
revision = '50ae7d1a8db2'
down_revision = '82b13e55681c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
