""" confimation added  migration

Revision ID: 653c1ea37ee3
Revises: e4465e172481
Create Date: 2021-08-15 15:41:10.623044

"""

# revision identifiers, used by Alembic.
revision = '653c1ea37ee3'
down_revision = 'e4465e172481'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
