"""Removed likes

Revision ID: 84b60cad4ea6
Revises: 5e876b2cea19
Create Date: 2021-08-17 11:36:31.475506

"""

# revision identifiers, used by Alembic.
revision = '84b60cad4ea6'
down_revision = '5e876b2cea19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
