"""Added dislike table

Revision ID: 8ffd2050ee69
Revises: 84b60cad4ea6
Create Date: 2021-08-17 12:58:16.584785

"""

# revision identifiers, used by Alembic.
revision = '8ffd2050ee69'
down_revision = '84b60cad4ea6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitches_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dislikes')
    # ### end Alembic commands ###
