"""Renamed name

Revision ID: a427d0eb0f3e
Revises: 8751eb55e256
Create Date: 2021-08-15 23:16:35.568169

"""

# revision identifiers, used by Alembic.
revision = 'a427d0eb0f3e'
down_revision = '8751eb55e256'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_body', sa.String(length=64), nullable=True))
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_body')
    # ### end Alembic commands ###
