"""Created comments

Revision ID: fa4f694e986a
Revises: 8c268b7acf17
Create Date: 2021-08-16 21:48:43.079233

"""

# revision identifiers, used by Alembic.
revision = 'fa4f694e986a'
down_revision = '8c268b7acf17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###
